export const PROVINCE_DETAIL_DATA = {
  // --- SUMATERA (10 Provinsi) ---
  Aceh: {
    capital: "Banda Aceh",
    population: "5.407.900",
    area: "57.956 km²",
    established: "1956",
    motto: "Pancacita",
    traditionalHouse: "Rumoh Aceh",
    traditionalDance: "Tari Saman",
    traditionalClothing: "Ulee Balang",
    localLanguages: ["Aceh", "Gayo", "Alas"],
    famousPlaces: [
      "Masjid Raya Baiturrahman",
      "Museum Tsunami",
      "Pulau Weh",
      "Danau Laut Tawar",
    ],
    signature_foods: ["Mie Aceh", "Ayam Tangkap", "Kuah Pliek U"],
    mainIndustries: ["Migas", "Pertanian", "Perikanan"],
    naturalResources: ["Minyak Bumi", "Gas Alam", "Kopi"],
  },
  "Sumatera Utara": {
    capital: "Medan",
    population: "15.115.206",
    area: "72.981 km²",
    established: "1948",
    motto: "Tekun Berkarya, Hidup Sejahtera, Mulia Berbudaya",
    traditionalHouse: "Rumah Bolon",
    traditionalDance: "Tari Tor-Tor",
    traditionalClothing: "Ulos",
    localLanguages: ["Batak", "Melayu", "Nias"],
    famousPlaces: ["Danau Toba", "Istana Maimun", "Bukit Lawang", "Berastagi"],
    signature_foods: ["Bika Ambon", "Arsik", "Saksang", "Durian Medan"],
    mainIndustries: ["Perkebunan", "Industri Pengolahan", "Pariwisata"],
    naturalResources: ["Kelapa Sawit", "Karet", "Kopi"],
  },
  "Sumatera Barat": {
    capital: "Padang",
    population: "5.640.629",
    area: "42.012 km²",
    established: "1957",
    motto: "Tuah Sakato",
    traditionalHouse: "Rumah Gadang",
    traditionalDance: "Tari Piring",
    traditionalClothing: "Bundo Kanduang",
    localLanguages: ["Minangkabau"],
    famousPlaces: [
      "Jam Gadang",
      "Istana Pagaruyung",
      "Danau Maninjau",
      "Kepulauan Mentawai",
    ],
    signature_foods: ["Rendang", "Sate Padang", "Dendeng Balado"],
    mainIndustries: ["Pertanian", "Pariwisata", "Industri Semen"],
    naturalResources: ["Batu Kapur", "Batubara", "Kelapa Sawit"],
  },
  Riau: {
    capital: "Pekanbaru",
    population: "6.614.384",
    area: "87.023 km²",
    established: "1957",
    motto: "Bumi Bertuah Negeri Beradat",
    traditionalHouse: "Selaso Jatuh Kembar",
    traditionalDance: "Tari Zapin",
    traditionalClothing: "Teluk Belanga",
    localLanguages: ["Melayu"],
    famousPlaces: ["Istana Siak", "Candi Muara Takus", "Masjid Agung An-Nur"],
    signature_foods: ["Gulai Ikan Patin", "Bolu Kemojo", "Mie Sagu"],
    mainIndustries: ["Perkebunan", "Migas", "Kehutanan"],
    naturalResources: ["Minyak Bumi", "Kelapa Sawit", "Karet"],
  },
  "Kepulauan Riau": {
    capital: "Tanjungpinang",
    population: "2.179.841",
    area: "8.201 km²",
    established: "2002",
    motto: "Berpancang Amanah Bersauh Marwah",
    traditionalHouse: "Rumah Belah Bubung",
    traditionalDance: "Tari Persembahan",
    traditionalClothing: "Kebaya Labuh",
    localLanguages: ["Melayu"],
    famousPlaces: [
      "Pulau Bintan",
      "Jembatan Barelang",
      "Masjid Raya Sultan Riau",
    ],
    signature_foods: ["Gonggong", "Otak-otak", "Mie Lendir"],
    mainIndustries: ["Pariwisata", "Elektronik", "Maritim"],
    naturalResources: ["Timah", "Bauksit", "Gas Alam"],
  },
  Jambi: {
    capital: "Jambi",
    population: "3.679.168",
    area: "50.058 km²",
    established: "1957",
    motto: "Sepucuk Jambi Sembilan Lurah",
    traditionalHouse: "Rumah Panggung Kajang Leko",
    traditionalDance: "Tari Sekapur Sirih",
    traditionalClothing: "Baju Kurung Tanggung",
    localLanguages: ["Melayu Jambi", "Kerinci"],
    famousPlaces: ["Candi Muaro Jambi", "Gunung Kerinci", "Danau Gunung Tujuh"],
    signature_foods: ["Tempoyak", "Gulai Tepek Ikan", "Mie Celor"],
    mainIndustries: ["Perkebunan", "Pertambangan", "Kehutanan"],
    naturalResources: ["Kelapa Sawit", "Karet", "Batubara"],
  },
  "Sumatera Selatan": {
    capital: "Palembang",
    population: "8.657.008",
    area: "91.592 km²",
    established: "1950",
    motto: "Bersatu Teguh",
    traditionalHouse: "Rumah Limas",
    traditionalDance: "Tari Gending Sriwijaya",
    traditionalClothing: "Aesan Gede",
    localLanguages: ["Melayu Palembang", "Komering"],
    famousPlaces: ["Jembatan Ampera", "Pulau Kemaro", "Jakabaring Sport City"],
    signature_foods: ["Pempek", "Tekwan", "Pindang Patin"],
    mainIndustries: ["Pertambangan", "Perkebunan", "Industri Pengolahan"],
    naturalResources: ["Batubara", "Gas Alam", "Karet"],
  },
  "Kepulauan Bangka Belitung": {
    capital: "Pangkalpinang",
    population: "1.494.621",
    area: "16.424 km²",
    established: "2000",
    motto: "Serumpun Sebalai",
    traditionalHouse: "Rumah Rakit",
    traditionalDance: "Tari Campak",
    traditionalClothing: "Paksian",
    localLanguages: ["Melayu Bangka", "Melayu Belitung"],
    famousPlaces: [
      "Pantai Tanjung Tinggi",
      "Museum Kata Andrea Hirata",
      "Danau Kaolin",
    ],
    signature_foods: ["Lempah Kuning", "Mie Belitung", "Martabak Bangka"],
    mainIndustries: ["Pertambangan", "Pariwisata", "Pertanian"],
    naturalResources: ["Timah", "Lada", "Kaolin"],
  },
  Bengkulu: {
    capital: "Bengkulu",
    population: "2.060.092",
    area: "19.919 km²",
    established: "1968",
    motto: "Sekundang Setungguan",
    traditionalHouse: "Rumah Bubungan Lima",
    traditionalDance: "Tari Andun",
    traditionalClothing: "Rejang Lebong",
    localLanguages: ["Melayu Bengkulu", "Rejang", "Serawai"],
    famousPlaces: [
      "Benteng Marlborough",
      "Rumah Pengasingan Bung Karno",
      "Pantai Panjang",
    ],
    signature_foods: ["Pendap", "Bagar Hiu", "Kue Tat"],
    mainIndustries: ["Pertanian", "Perkebunan"],
    naturalResources: ["Batubara", "Emas", "Sawit"],
  },
  Lampung: {
    capital: "Bandar Lampung",
    population: "9.176.546",
    area: "34.623 km²",
    established: "1964",
    motto: "Sang Bumi Ruwa Jurai",
    traditionalHouse: "Nuwo Sesat",
    traditionalDance: "Tari Sigeh Pengunten",
    traditionalClothing: "Tulang Bawang",
    localLanguages: ["Lampung"],
    famousPlaces: ["Taman Nasional Way Kambas", "Teluk Kiluan", "Menara Siger"],
    signature_foods: ["Seruit", "Tempoyak", "Keripik Pisang"],
    mainIndustries: ["Pertanian", "Perkebunan", "Peternakan"],
    naturalResources: ["Kopi", "Lada", "Tebu"],
  },

  // --- JAWA (6 Provinsi) ---
  Banten: {
    capital: "Serang",
    population: "12.251.985",
    area: "9.662 km²",
    established: "2000",
    motto: "Iman Taqwa",
    traditionalHouse: "Rumah Baduy",
    traditionalDance: "Tari Rampak Bedug",
    traditionalClothing: "Pangsi",
    localLanguages: ["Sunda", "Jawa Banten"],
    famousPlaces: [
      "Taman Nasional Ujung Kulon",
      "Pantai Anyer",
      "Masjid Agung Banten",
    ],
    signature_foods: ["Sate Bandeng", "Rabeg", "Nasi Sumsum"],
    mainIndustries: ["Industri Manufaktur", "Pariwisata", "Perhubungan"],
    naturalResources: ["Baja", "Hasil Laut"],
  },
  "Jakarta Raya": {
    capital: "Jakarta",
    population: "10.679.951",
    area: "661 km²",
    established: "1961",
    motto: "Jaya Raya",
    traditionalHouse: "Rumah Kebaya",
    traditionalDance: "Tari Yapong",
    traditionalClothing: "Sadariah & Kebaya Encim",
    localLanguages: ["Betawi", "Indonesia"],
    famousPlaces: ["Monas", "Kota Tua", "TMII", "Ancol"],
    signature_foods: ["Kerak Telor", "Soto Betawi", "Gado-gado"],
    mainIndustries: ["Jasa", "Keuangan", "Perdagangan"],
    naturalResources: ["Terbatas (Perkotaan)"],
  },
  "Jawa Barat": {
    capital: "Bandung",
    population: "49.405.808",
    area: "35.377 km²",
    established: "1950",
    motto: "Gemah Ripah Repeh Rapih",
    traditionalHouse: "Rumah Kasepuhan",
    traditionalDance: "Tari Jaipong",
    traditionalClothing: "Kebaya Sunda",
    localLanguages: ["Sunda"],
    famousPlaces: ["Gedung Sate", "Kawah Putih", "Tangkuban Perahu"],
    signature_foods: ["Batagor", "Peuyeum", "Nasi Liwet", "Surabi"],
    mainIndustries: ["Manufaktur", "Tekstil", "Pariwisata"],
    naturalResources: ["Teh", "Padi", "Panas Bumi"],
  },
  "Jawa Tengah": {
    capital: "Semarang",
    population: "37.032.410",
    area: "32.800 km²",
    established: "1950",
    motto: "Prasetya Ulah Sakti Bhakti Praja",
    traditionalHouse: "Rumah Joglo",
    traditionalDance: "Tari Gambyong",
    traditionalClothing: "Jawi Jangkep",
    localLanguages: ["Jawa"],
    famousPlaces: ["Candi Borobudur", "Lawang Sewu", "Dataran Tinggi Dieng"],
    signature_foods: ["Lumpia", "Gudeg (Solo)", "Nasi Gandul", "Mendoan"],
    mainIndustries: ["Pertanian", "Industri Pengolahan", "Pariwisata"],
    naturalResources: ["Padi", "Tembakau", "Kayu Jati"],
  },
  "Daerah Istimewa Yogyakarta": {
    capital: "Yogyakarta",
    population: "3.761.870",
    area: "3.133 km²",
    established: "1950",
    motto: "Hamemayu Hayuning Bawana",
    traditionalHouse: "Bangsal Kencono",
    traditionalDance: "Tari Bedhaya Ketawang",
    traditionalClothing: "Surjan & Kebaya",
    localLanguages: ["Jawa"],
    famousPlaces: ["Keraton Yogyakarta", "Jalan Malioboro", "Candi Prambanan"],
    signature_foods: ["Gudeg", "Bakpia", "Sate Klatak"],
    mainIndustries: ["Pariwisata", "Pendidikan", "Ekonomi Kreatif"],
    naturalResources: ["Pasir Besi", "Tanah Liat"],
  },
  "Jawa Timur": {
    capital: "Surabaya",
    population: "41.149.974",
    area: "47.803 km²",
    established: "1950",
    motto: "Jer Basuki Mawa Beya",
    traditionalHouse: "Joglo Situbondo",
    traditionalDance: "Tari Remo",
    traditionalClothing: "Pesa'an (Madura)",
    localLanguages: ["Jawa", "Madura", "Osing"],
    famousPlaces: ["Gunung Bromo", "Kawah Ijen", "Jatim Park"],
    signature_foods: ["Rawon", "Rujak Cingur", "Soto Lamongan"],
    mainIndustries: ["Industri", "Perdagangan", "Pertanian"],
    naturalResources: ["Migas", "Tembakau", "Tebu"],
  },

  // --- BALI & NUSA TENGGARA (3 Provinsi) ---
  Bali: {
    capital: "Denpasar",
    population: "4.414.400",
    area: "5.780 km²",
    established: "1958",
    motto: "Bali Dwipa Jaya",
    traditionalHouse: "Gapura Candi Bentar",
    traditionalDance: "Tari Kecak",
    traditionalClothing: "Payas Agung",
    localLanguages: ["Bali"],
    famousPlaces: ["Pura Tanah Lot", "Ubud", "Pantai Kuta", "Pura Besakih"],
    signature_foods: ["Ayam Betutu", "Sate Lilit", "Babi Guling"],
    mainIndustries: ["Pariwisata", "Pertanian", "Kerajinan"],
    naturalResources: ["Padi", "Kopi", "Hasil Laut"],
  },
  "Nusa Tenggara Barat": {
    capital: "Mataram",
    population: "5.473.671",
    area: "18.572 km²",
    established: "1958",
    motto: "Beriman dan Bersaing",
    traditionalHouse: "Dalam Loka",
    traditionalDance: "Tari Gandrung Lombok",
    traditionalClothing: "Rimpu",
    localLanguages: ["Sasak", "Samawa", "Mbojo"],
    famousPlaces: ["Gunung Rinjani", "Sirkuit Mandalika", "Gili Trawangan"],
    signature_foods: ["Ayam Taliwang", "Plecing Kangkung", "Sate Bulayak"],
    mainIndustries: ["Pariwisata", "Pertambangan", "Pertanian"],
    naturalResources: ["Emas", "Tembaga", "Mutiara"],
  },
  "Nusa Tenggara Timur": {
    capital: "Kupang",
    population: "5.541.394",
    area: "48.718 km²",
    established: "1958",
    motto: "Fidelitas",
    traditionalHouse: "Musalaki",
    traditionalDance: "Tari Caci",
    traditionalClothing: "Kain Tenun Ikat",
    localLanguages: ["Dawan", "Manggarai", "Sumba"],
    famousPlaces: ["Taman Nasional Komodo", "Danau Kelimutu", "Pulau Padar"],
    signature_foods: ["Se'i Daging", "Jagung Bose", "Kolo"],
    mainIndustries: ["Pertanian", "Peternakan", "Pariwisata"],
    naturalResources: ["Cendana", "Marmer", "Mangan"],
  },

  // --- KALIMANTAN (5 Provinsi) ---
  "Kalimantan Barat": {
    capital: "Pontianak",
    population: "5.560.017",
    area: "147.307 km²",
    established: "1957",
    motto: "Akcaya",
    traditionalHouse: "Rumah Radakng",
    traditionalDance: "Tari Monong",
    traditionalClothing: "King Baba & King Bibinge",
    localLanguages: ["Dayak", "Melayu", "Tionghoa"],
    famousPlaces: ["Tugu Khatulistiwa", "Singkawang", "Bukit Kelam"],
    signature_foods: ["Bubur Pedas", "Chai Kue", "Pengkang"],
    mainIndustries: ["Perkebunan", "Pertambangan"],
    naturalResources: ["Bauksit", "Sawit", "Karet"],
  },
  "Kalimantan Tengah": {
    capital: "Palangka Raya",
    population: "2.741.000",
    area: "153.564 km²",
    established: "1957",
    motto: "Isen Mulang",
    traditionalHouse: "Rumah Betang",
    traditionalDance: "Tari Balean Dadas",
    traditionalClothing: "Sangkarut",
    localLanguages: ["Dayak Ngaju", "Dayak Maanyan"],
    famousPlaces: [
      "Taman Nasional Tanjung Puting",
      "Sungai Kahayan",
      "Bukit Batu",
    ],
    signature_foods: ["Juhu Singkah", "Wadi", "Kalumpe"],
    mainIndustries: ["Pertambangan", "Perkebunan"],
    naturalResources: ["Batubara", "Emas", "Sawit"],
  },
  "Kalimantan Selatan": {
    capital: "Banjarbaru",
    population: "4.182.000",
    area: "38.744 km²",
    established: "1950",
    motto: "Waja Sampai Kaputing",
    traditionalHouse: "Rumah Bubungan Tinggi",
    traditionalDance: "Tari Baksa Kembang",
    traditionalClothing: "Baamar Galung Pancar Matahari",
    localLanguages: ["Banjar"],
    famousPlaces: [
      "Pasar Terapung Lok Baintan",
      "Jembatan Barito",
      "Bukit Rimpi",
    ],
    signature_foods: ["Soto Banjar", "Ketupat Kandangan", "Mandai"],
    mainIndustries: ["Pertambangan", "Perdagangan"],
    naturalResources: ["Batubara", "Intan", "Bijih Besi"],
  },
  "Kalimantan Timur": {
    capital: "Samarinda",
    population: "3.909.740",
    area: "129.066 km²",
    established: "1957",
    motto: "Ruhui Rahayu",
    traditionalHouse: "Rumah Lamin",
    traditionalDance: "Tari Gong",
    traditionalClothing: "Sapei Sapaq",
    localLanguages: ["Dayak", "Kutai", "Banjar"],
    famousPlaces: ["Titik Nol IKN", "Pulau Derawan", "Sungai Mahakam"],
    signature_foods: ["Nasi Bekepor", "Ayam Cincane", "Gence Ruan"],
    mainIndustries: ["Pertambangan", "Migas", "Kehutanan"],
    naturalResources: ["Batubara", "Minyak Bumi", "Gas Alam"],
  },
  "Kalimantan Utara": {
    capital: "Tanjung Selor",
    population: "726.000",
    area: "75.467 km²",
    established: "2012",
    motto: "Benuanta",
    traditionalHouse: "Rumah Baloy",
    traditionalDance: "Tari Magunatip",
    traditionalClothing: "Ta'a dan Sapei Sapaq",
    localLanguages: ["Tidung", "Dayak"],
    famousPlaces: [
      "Hutan Mangrove Tarakan",
      "Air Terjun Gunung Rian",
      "Kayan Mentarang",
    ],
    signature_foods: ["Kepiting Soka", "Nasi Subut", "Sate Temburung"],
    mainIndustries: ["Pertambangan", "Kehutanan"],
    naturalResources: ["Minyak Bumi", "Gas Alam", "Batubara"],
  },

  // --- SULAWESI (6 Provinsi) ---
  "Sulawesi Utara": {
    capital: "Manado",
    population: "2.666.000",
    area: "13.892 km²",
    established: "1964",
    motto: "Si Tou Timou Tumou Tou",
    traditionalHouse: "Walewangko",
    traditionalDance: "Tari Maengket",
    traditionalClothing: "Laku Tepu",
    localLanguages: ["Manado", "Minahasa", "Sangihe"],
    famousPlaces: [
      "Taman Laut Bunaken",
      "Danau Tondano",
      "Patung Yesus Memberkati",
    ],
    signature_foods: ["Bubur Manado (Tinutuan)", "Ayam Woku", "Klappertaart"],
    mainIndustries: ["Pariwisata", "Perikanan", "Pertanian"],
    naturalResources: ["Kopra", "Pala", "Emas"],
  },
  Gorontalo: {
    capital: "Gorontalo",
    population: "1.192.000",
    area: "11.257 km²",
    established: "2000",
    motto: "Adat Bersendikan Syara, Syara Bersendikan Kitabullah",
    traditionalHouse: "Dulohupa",
    traditionalDance: "Tari Dana-Dana",
    traditionalClothing: "Biliu dan Makuta",
    localLanguages: ["Gorontalo"],
    famousPlaces: ["Benteng Otanaha", "Pulo Cinta", "Taman Laut Olele"],
    signature_foods: ["Binte Biluhuta", "Ayam Iloni", "Tili Aya"],
    mainIndustries: ["Pertanian", "Perikanan"],
    naturalResources: ["Jagung", "Emas", "Tembaga"],
  },
  "Sulawesi Tengah": {
    capital: "Palu",
    population: "3.066.000",
    area: "61.841 km²",
    established: "1964",
    motto: "Nosarara Nosabatutu",
    traditionalHouse: "Souraja",
    traditionalDance: "Tari Lumense",
    traditionalClothing: "Baju Nggembe",
    localLanguages: ["Kaili", "Pamona"],
    famousPlaces: [
      "Danau Poso",
      "Taman Nasional Lore Lindu",
      "Kepulauan Togean",
    ],
    signature_foods: ["Kaledo", "Duo Sale", "Uta Dada"],
    mainIndustries: ["Pertambangan", "Perkebunan"],
    naturalResources: ["Nikel", "Kakao", "Emas"],
  },
  "Sulawesi Barat": {
    capital: "Mamuju",
    population: "1.458.000",
    area: "16.787 km²",
    established: "2004",
    motto: "Mellete Diatonganan",
    traditionalHouse: "Rumah Boyang",
    traditionalDance: "Tari Patuddu",
    traditionalClothing: "Pattuqduq Towaine",
    localLanguages: ["Mandar"],
    famousPlaces: [
      "Pantai Manakarra",
      "Air Terjun Tamasapi",
      "Pulau Karampuang",
    ],
    signature_foods: ["Bau Peapi", "Jepa", "Golla Kambu"],
    mainIndustries: ["Perkebunan", "Pertanian"],
    naturalResources: ["Kakao", "Kopi", "Minyak Bumi"],
  },
  "Sulawesi Selatan": {
    capital: "Makassar",
    population: "9.225.000",
    area: "46.717 km²",
    established: "1964",
    motto: "Toddo Puli",
    traditionalHouse: "Tongkonan",
    traditionalDance: "Tari Kipas Pakarena",
    traditionalClothing: "Baju Bodo",
    localLanguages: ["Makassar", "Bugis", "Toraja"],
    famousPlaces: [
      "Pantai Losari",
      "Tana Toraja",
      "Taman Nasional Bantimurung",
    ],
    signature_foods: ["Coto Makassar", "Sop Konro", "Pisang Epe"],
    mainIndustries: ["Pertanian", "Perikanan", "Pertambangan"],
    naturalResources: ["Nikel", "Padi", "Kakao"],
  },
  "Sulawesi Tenggara": {
    capital: "Kendari",
    population: "2.704.000",
    area: "38.067 km²",
    established: "1964",
    motto: "Bolimo Karo Somanamo Lipu",
    traditionalHouse: "Banua Tada",
    traditionalDance: "Tari Lulo",
    traditionalClothing: "Babu Nggawi",
    localLanguages: ["Tolaki", "Buton", "Muna"],
    famousPlaces: [
      "Taman Nasional Wakatobi",
      "Pulau Labengki",
      "Benteng Keraton Buton",
    ],
    signature_foods: ["Sinonggi", "Lapa-lapa", "Sate Pokea"],
    mainIndustries: ["Pertambangan", "Pariwisata"],
    naturalResources: ["Nikel", "Aspal", "Emas"],
  },

  // --- MALUKU & PAPUA (8 Provinsi) ---
  Maluku: {
    capital: "Ambon",
    population: "1.881.000",
    area: "46.914 km²",
    established: "1958",
    motto: "Siwalima",
    traditionalHouse: "Baileo",
    traditionalDance: "Tari Lenso",
    traditionalClothing: "Baju Cele",
    localLanguages: ["Ambon"],
    famousPlaces: ["Pantai Natsepa", "Benteng Amsterdam", "Kepulauan Banda"],
    signature_foods: ["Papeda", "Ikan Kuah Kuning", "Sambal Colo-colo"],
    mainIndustries: ["Perikanan", "Pariwisata"],
    naturalResources: ["Pala", "Cengkeh", "Ikan"],
  },
  "Maluku Utara": {
    capital: "Sofifi",
    population: "1.319.000",
    area: "31.982 km²",
    established: "1999",
    motto: "Marimoi Ngone Futuru",
    traditionalHouse: "Sasadu",
    traditionalDance: "Tari Soya-Soya",
    traditionalClothing: "Manteren Lamo",
    localLanguages: ["Ternate", "Tidore"],
    famousPlaces: ["Gunung Gamalama", "Danau Tolire", "Pulau Morotai"],
    signature_foods: ["Gohu Ikan", "Gatang Kenari", "Popeda"],
    mainIndustries: ["Pertambangan", "Perkebunan"],
    naturalResources: ["Nikel", "Emas", "Rempah-rempah"],
  },
  Papua: {
    capital: "Jayapura",
    population: "1.035.000", // Pasca pemekaran
    area: "81.049 km²",
    established: "1963",
    motto: "Karya Swadaya",
    traditionalHouse: "Kariwari",
    traditionalDance: "Tari Yospan",
    traditionalClothing: "Koteka & Rok Rumbai",
    localLanguages: ["Sentani", "Tobati"],
    famousPlaces: ["Danau Sentani", "Jembatan Merah Youtefa", "Pantai Base G"],
    signature_foods: ["Papeda", "Ikan Bungkus", "Udang Selingkuh"],
    mainIndustries: ["Jasa", "Pariwisata"],
    naturalResources: ["Emas", "Tembaga", "Kayu"],
  },
  "Papua Barat": {
    capital: "Manokwari",
    population: "561.000",
    area: "60.275 km²",
    established: "1999",
    motto: "Cintaku Negeriku",
    traditionalHouse: "Mod Aki Aksa",
    traditionalDance: "Tari Perang",
    traditionalClothing: "Ewer",
    localLanguages: ["Hatam", "Moile"],
    famousPlaces: ["Pegunungan Arfak", "Teluk Doreri", "Pulau Mansinam"],
    signature_foods: ["Ikan Kuah Kuning", "Papeda", "Sate Ulat Sagu"],
    mainIndustries: ["Pertanian", "Pariwisata"],
    naturalResources: ["Kakao", "Pala", "Migas"],
  },
  "Papua Barat Daya": {
    // NEW
    capital: "Sorong",
    population: "613.100",
    area: "39.123 km²",
    established: "2022",
    motto: "Kitorang Kuat Karena Basudara",
    traditionalHouse: "Rumah Kaki Seribu",
    traditionalDance: "Tari Aluyen",
    traditionalClothing: "Baju Kain Rumput",
    localLanguages: ["Moi", "Maybrat"],
    famousPlaces: ["Raja Ampat", "Taman Burung Aimas", "Pulau Buaya"],
    signature_foods: ["Kue Lontar", "Papeda", "Ikan Bakar Manokwari"],
    mainIndustries: ["Pariwisata", "Migas"],
    naturalResources: ["Minyak Bumi", "Gas Alam", "Keindahan Laut"],
  },
  "Papua Tengah": {
    // NEW
    capital: "Nabire",
    population: "1.355.000",
    area: "66.129 km²",
    established: "2022",
    motto: "Karya Swadaya",
    traditionalHouse: "Honai",
    traditionalDance: "Tari Yospan",
    traditionalClothing: "Koteka",
    localLanguages: ["Mee", "Amungme", "Moni"],
    famousPlaces: [
      "Taman Nasional Lorentz",
      "Puncak Jaya (Carstensz)",
      "Tambang Grasberg",
    ],
    signature_foods: ["Ubi Jalar (Hipere)", "Sayur Paku", "Babi Bakar Batu"],
    mainIndustries: ["Pertambangan"],
    naturalResources: ["Emas", "Tembaga", "Perak"],
  },
  "Papua Selatan": {
    // NEW
    capital: "Merauke",
    population: "534.000",
    area: "117.849 km²",
    established: "2022",
    motto: "Anim Ha",
    traditionalHouse: "Gotad",
    traditionalDance: "Tari Gatzi",
    traditionalClothing: "Pakaian Adat Marind",
    localLanguages: ["Marind", "Asmat"],
    famousPlaces: [
      "Taman Nasional Wasur",
      "Musamus (Rumah Semut)",
      "Perbatasan Sota",
    ],
    signature_foods: ["Sagu Sep", "Daging Rusa", "Ikan Gastor"],
    mainIndustries: ["Pertanian", "Perkebunan"],
    naturalResources: ["Padi", "Tebu", "Perikanan Darat"],
  },
  "Papua Pegunungan": {
    // NEW
    capital: "Wamena",
    population: "1.448.000",
    area: "51.213 km²",
    established: "2022",
    motto: "Karya Swadaya",
    traditionalHouse: "Honai (Silimo)",
    traditionalDance: "Tari Perang Dani",
    traditionalClothing: "Koteka (Holim)",
    localLanguages: ["Dani", "Lani", "Yali"],
    famousPlaces: ["Lembah Baliem", "Danau Habema", "Festival Lembah Baliem"],
    signature_foods: ["Udang Selingkuh", "Hipere (Ubi)", "Bakar Batu"],
    mainIndustries: ["Pertanian"],
    naturalResources: ["Pertanian Dataran Tinggi", "Pariwisata Budaya"],
  },
};

export const getProvinceByName = ({ name }) => {
  return PROVINCE_DETAIL_DATA[name] || null;
};
